# Generated by Django 4.2.2 on 2023-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/slider/%y/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
