# Generated by Django 4.2.2 on 2023-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Linkedin_link',
            new_name='linkedin_link',
        ),
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='https://youtube.com', max_length=500),
            preserve_default=False,
        ),
    ]
