# Generated by Django 4.2.4 on 2023-08-03 11:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubers',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('sony', 'sony'), ('red', 'red'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('vlogs', 'vlogs'), ('comedy', 'comdey'), ('gaming', 'gaming'), ('standup', 'standup'), ('anime', 'anime'), ('film_making', 'film_making'), ('song', 'song'), ('motivation', 'motivation'), ('cooking', 'cooking'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
